blank_issues_enabled: true
contact_links:
  - name: ðŸ¤” Support/Usage Question
    url: https://community.openhab.org
    about: Feel free to ask anything
  - name: ðŸ“– JS Scripting Documentation
    url: https://next.openhab.org/addons/automation/jsscripting/
    about: Official documentation
  - name: ðŸ“– openHAB JavaScript Library advanced documentation (JSDoc)
    url: https://openhab.github.io/openhab-js/
    about: JSDoc library documentation
